# Generated by Django 3.0.2 on 2020-02-08 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20200208_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(default='Title', max_length=120, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_id',
            field=models.IntegerField(default=0, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_text',
            field=models.CharField(max_length=5000, verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='article',
            name='author_name',
            field=models.CharField(default='Somebody', max_length=32, verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='article',
            name='publish_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='article',
            name='rating',
            field=models.IntegerField(default=0, verbose_name='rating'),
        ),
    ]
